spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: POST-SERVICE
          uri: lb://POST-SERVICE
          predicates:
            - Path=/api/posts/**
        - id: COMMENT-SERVICE
          uri: lb://COMMENT-SERVICE
          predicates:
            - Path=/api/comments/**
        # Add more routes for other microservices as needed

server:
  port: 8083


eureka:
  client:
    register-with-eureka: true                    # Register this client with Eureka server
    fetch-registry: true                          # Fetch registry information from the Eureka server
    service-url:
      defaultZone: http://localhost:8761/eureka/  # URL of the Eureka Server
  instance:
    prefer-ip-address: true
    instance-id: API-GATEWAY
